# Generated by Django 4.1.4 on 2022-12-07 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extent', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('website_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=250)),
                ('profile_image_url', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=250)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TripExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=150)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trouvailleapi.experience')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trouvailleapi.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trouvailleapi.destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trouvailleapi.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(through='trouvailleapi.TripDestination', to='trouvailleapi.destination'),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_trips', to='trouvailleapi.duration'),
        ),
        migrations.AddField(
            model_name='trip',
            name='experiences',
            field=models.ManyToManyField(through='trouvailleapi.TripExperience', to='trouvailleapi.experience'),
        ),
        migrations.AddField(
            model_name='trip',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_trips', to='trouvailleapi.season'),
        ),
        migrations.AddField(
            model_name='trip',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styled_trips', to='trouvailleapi.style'),
        ),
        migrations.AddField(
            model_name='trip',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveled_trips', to='trouvailleapi.traveler'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='trouvailleapi.experiencetype'),
        ),
    ]
