# Generated by Django 4.1.4 on 2022-12-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
    ]
