# Generated by Django 4.2.10 on 2024-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
