# Generated by Django 4.2.10 on 2024-02-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0003_alter_experience_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
