# Generated by Django 4.1.4 on 2022-12-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0003_favoritetrip_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritetrip',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_trips', to='trouvailleapi.traveler'),
        ),
    ]
