# Generated by Django 4.2.10 on 2024-02-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0004_alter_experience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
