# Generated by Django 4.1.4 on 2022-12-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0004_alter_favoritetrip_traveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritetrip',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_trips', to='trouvailleapi.traveler'),
        ),
    ]
