# Generated by Django 4.2.10 on 2024-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0005_alter_experience_address_alter_experience_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='cover_img',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='profile_img',
            field=models.CharField(max_length=500),
        ),
    ]
