# Generated by Django 4.1.4 on 2022-12-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0005_alter_favoritetrip_traveler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='profile_image_url',
            new_name='profile_img',
        ),
        migrations.AddField(
            model_name='traveler',
            name='cover_img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
