# Generated by Django 4.1.4 on 2022-12-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0006_rename_profile_image_url_traveler_profile_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover_img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
