# Generated by Django 4.2.10 on 2024-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0006_alter_traveler_cover_img_alter_traveler_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cover_img',
            field=models.CharField(default='', max_length=250),
        ),
    ]
