# Generated by Django 4.2.10 on 2024-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0007_alter_trip_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cover_img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
