# Generated by Django 4.1.4 on 2023-01-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0007_trip_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='website_url',
            field=models.CharField(max_length=100),
        ),
    ]
