# Generated by Django 4.1.4 on 2023-01-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0008_experience_image_alter_experience_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(related_name='destination_trips', through='trouvailleapi.TripDestination', to='trouvailleapi.destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='experiences',
            field=models.ManyToManyField(related_name='experience_trips', through='trouvailleapi.TripExperience', to='trouvailleapi.experience'),
        ),
    ]
