# Generated by Django 4.2.10 on 2024-02-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0009_alter_trip_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
