# Generated by Django 4.1.4 on 2023-01-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
