# Generated by Django 4.1.4 on 2023-01-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0011_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripexperience',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_trip_experiences', to='trouvailleapi.experience'),
        ),
    ]
