# Generated by Django 4.2.10 on 2024-02-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvailleapi', '0011_alter_trip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.CharField(max_length=250),
        ),
    ]
